
# Add local
export PATH=${HOME}/.local/bin:${PATH}

# FOSS PATH
export PATH=/cad/foss/tools/klayout:${PATH}
export PATH=/cad/foss/tools/magic/bin:${PATH}
export PATH=/cad/foss/tools/netgen/bin:${PATH}
export PATH=/cad/foss/tools/xschem/bin:${PATH}
export PATH=/cad/foss/tools/gaw/bin:${PATH}
export PATH=/cad/foss/tools/ngspice/bin:${PATH}
export PATH=/cad/foss/tools/openroad/bin:${PATH}
export PATH=/cad/foss/tools/yosys/bin:${PATH}
export PATH=/cad/foss/tools/iverilog/bin:${PATH}

export PDK_ROOT=${HOME}/PDK
export PDK=sky130A

alias klayout='KLAYOUT_HOME=.klayout klayout -e'
alias openroad='LD_LIBRARY_PATH=/usr/local/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} openroad'
